const isPrime = require('../../code-wars/6-kyu/isprime')

describe('Is prime', () => {
  it('Is prime test cases', () => {
    expect(isPrime(-1)).toBeFalsy()
    expect(isPrime(1)).toBeFalsy()
    expect(isPrime(4)).toBeFalsy()
    expect(isPrime(9)).toBeFalsy()
    expect(isPrime(10)).toBeFalsy()
    expect(isPrime(81)).toBeFalsy()
    expect(isPrime(100)).toBeFalsy()
    expect(isPrime(9)).toBeFalsy()
    expect(isPrime(2)).toBeTruthy()
    expect(isPrime(3)).toBeTruthy()
    expect(isPrime(5)).toBeTruthy()
    expect(isPrime(11)).toBeTruthy()
    expect(isPrime(67)).toBeTruthy()
    expect(isPrime(79)).toBeTruthy()
    expect(isPrime(97)).toBeTruthy()
  })
})
